server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bikers
    username: root
    password: 12345
  application:
    name: app-service

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
appDescription: "Bikers project"
appVersion: "1.0.0"


feign:
  module:
    mechanic: "localhost:8081/api/mechanic/v1"
    brand: "localhost:8084/api/brand/v1"


resilience4j.circuitbreaker:
  instances:
    mechanicA:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 4
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
    brandB:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 4
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
