spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mongoBrands
  application:
    name: brand-service

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8087/eureka/     