
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8087/eureka/  

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: mechanic-service
          uri: lb://mechanic-service
          predicates:
            - Path=/api/app/v1/mechanic/**
        - id: brand-service
          uri: lb://brand-service
          predicates:
            - Path=/api/app/v1/brand/**
        - id: app-service
          uri: lb://app-service
          predicates:
            - Path=/api/app/v1/**    
