server:
  port: 8081
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mongoMechanics

  application:
    name: mechanic-service

eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8087/eureka/       

feign:
  module:
    brand: "localhost:8084/api/app/v1/brand"      